# Generated by Django 5.0.1 on 2024-01-07 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Название цвета', max_length=40)),
                ('HEX', models.CharField(help_text='HEX данного цвета', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEmbroidery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Название типа вышивки', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Embroidery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Название схемы', max_length=40)),
                ('SizeX', models.IntegerField(help_text='Количество клеток по горизонтали')),
                ('SizeY', models.IntegerField(help_text='Количество клеток по вертикали')),
                ('Scheme', models.TextField(help_text='Массив цветов')),
                ('Date', models.DateField(auto_now_add=True)),
                ('User_id', models.ForeignKey(help_text='Создатель', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Type_id', models.ForeignKey(help_text='Тип вышивки', on_delete=django.db.models.deletion.CASCADE, to='catalog.typeembroidery')),
            ],
        ),
    ]
