# Generated by Django 5.0.1 on 2024-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_snippet_highlighted_snippet_language_snippet_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embroidery',
            name='Scheme',
        ),
        migrations.RemoveField(
            model_name='embroidery',
            name='SizeX',
        ),
        migrations.RemoveField(
            model_name='embroidery',
            name='SizeY',
        ),
        migrations.AddField(
            model_name='embroidery',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
