# Generated by Django 5.0.1 on 2024-05-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_embroidery_scheme_remove_embroidery_sizex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embroidery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
