# Generated by Django 5.0.1 on 2024-05-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_embroidery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='embroidery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
